#assembler_command = "mips-linux-gnu-as -G0 -Iinclude -mips3 -mabi=32"
compiler_type = "gcc"

[preserve_macros]
"gs?[DS]P.*" = "void"
OVERRIDE_FLAG_CHECK = "int"
OS_K0_TO_PHYSICAL = "int"
"G_.*" = "int"
"TEXEL.*" = "int"
PRIMITIVE = "int"

#[decompme.compilers]
#"COMPILER_PATH=tools/gcc_kmc/linux/2.7.2" = "gcc2.7.2kmc"
